error-pages:
  env:
    TEMPLATE_NAME: connection

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      ingressClassName: traefik
      hosts:
        - host: error-pages.framsburg.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: error-pages
      tls:
        - hosts: [error-pages.framsburg.dev]
          secretName: error-pages-framsburg-dev-tls
