{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: argocd-server-external-callback-http*/}}
{{/*  annotations:*/}}
{{/*    cert-manager.io/cluster-issuer: letsencrypt-prod*/}}
{{/*    traefik.ingress.kubernetes.io/router.entrypoints: websecure*/}}
{{/*spec:*/}}
{{/*  ingressClassName: traefik*/}}
{{/*  rules:*/}}
{{/*    - host: argocd-callback.framsburg.dev*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /api/webhook*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: argo-cd-argocd-server*/}}
{{/*                port:*/}}
{{/*                  name: http*/}}
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*      - argocd-callback.framsburg.dev*/}}
{{/*      secretName: argocd-callback-framsburg-dev-tls*/}}
